### ISSUE TITLE
the input device is not a TTY

### ISSUE THREAD

**Issue by jupitern** [appleboy/ssh-action#22]
resolved

**Comment by jupitern** [comment]
resolved.

**Comment by matteoformenti** [comment]
Still receiving this error on ubuntu 18.04 using private key for login. This causes all my scripts that require any permission to fail for insufficient permissions. Can you share info about your fix? Thanks

**Comment by jupitern** [comment]
The issue I was having was that within the action I was doing ssh to another VM and there I was doing a docker exec -it containername
-it parameter is interactive mode. that was generating the error.
My guess is that your script is asking some input from the user like a Yes/no or a passsword or something. The commands should have parameters so that the user input is not requested.

**Comment by matteoformenti** [comment]
Thanks for sharing your experience, I've fixed my problem by checking files and folders permissions. Weirdly enough the problem was caused by a permission denied error
